export const data = [
    {id : 1,
    name: "Samsung A2", 
    category: "",
    // imagePath:require("").default,
    amount: "",
    discount: '',
    ratings: "",
    inStock: "",
    favorite: "",
    description: "",
 },

    {id : 2, 
    name: "I phone X", 
    category: "",
    // imagePath:require("").default,
    amount: "",
    discount: '',
    ratings: "",
    inStock: "",
    favorite: "",
    description: "",
 },

    {id : 3,
    name: "Nokia",
    category: "", 
    // imagePath:require("").default, 
    amount: "",
    discount: '',
    ratings: "",
    inStock: "",
    favorite: "",
    description: "",
},


    {id : 4,
    name: "Infinix",
    category: "", 
    // imagePath:require("").default, 
    amount: "",
    discount: '',
    ratings: "",
    inStock: "",
    favorite: "",
    description: "",
},
]

