export const data = [
    {id : 1,
    name: "Samsung A2", 
    category: "",
    imagePath:require("../images/images1.jpeg"),
    amount: "",
    discount: '',
    ratings: "",
    inStock: "",
    favorite: "",
    description: "",
 },

    {id : 2, 
    name: "I phone X", 
    category: "",
    imagePath:require("../images/images2.jpeg"),
    amount: "",
    discount: '',
    ratings: "",
    inStock: "",
    favorite: "",
    description: "",
 },

    {id : 3,
    name: "Nokia",
    category: "", 
    imagePath:require("../images/images3.jpeg"), 
    amount: "",
    discount: '',
    ratings: "",
    inStock: "",
    favorite: "",
    description: "",
},


    {id : 4,
    name: "Infinix",
    category: "", 
    imagePath:require("../images/images4.jpeg"), 
    amount: "",
    discount: '',
    ratings: "",
    inStock: "",
    favorite: "",
    description: "",
},
]

